version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Linter 
          command: npm run lint
      - run:
          name: Formatter 
          command: npm run prettier
      - run:
          name: Test 
          command: npm run test
      - run:
          name: Build  
          command: npm run build
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master