name: Main
on:
    push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Node
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Install dependencies
      - name: install
        run: |
         npm remove --save node-sass
         npm install --save node-sass
         npm install

      - name: linter
        run: npm run lint

      - name: Install npm v8
        run: npm i -g npm@8
        
      - name: Formatter
        run: npm run prettier

      - name: Test
        run: npm run test

      # Build the site
      - name: Build
        run: npm run build
